name: astrods

channels:
- conda-forge
- pytorch

dependencies:
- python=3.11.*
- numpy
- matplotlib
- graphviz
- pytorch
- torchvision
- pytorch-lightning
- cartopy
- pandas
- protobuf
- jupysql
- scikit-learn==1.5.*
- scikit-image==0.24.*
- scipy==1.14.*
- cython==3.0.11
- marimo>=0.8.14
- pip
